// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uohxbqotntxosvfcnfnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvaHhicW90bnR4b3N2ZmNuZm50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjA3MTEsImV4cCI6MjA2NDc5NjcxMX0.HBpzwOVfGqNUQjMo3jxo2KeaXHlZpe83GL94NmhcJI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});